---
title: "Upcoming interactive workshop at the National Open Science Festival: Stimulating Data (Re)Use"
description: [UU Research Data Management support](https://www.uu.nl/en/research/research-data-management) joins forces with the [FAIR Data & Software Track](https://www.uu.nl/en/research/open-science/knowledge-center/faq/fair-data-and-software) of the UU Open Science Program, and the [Utrecht Open Science Office](https://www.uu.nl/onderzoek/open-science/over-ons/projectteam) to host a 2-hour interactive session on data re(use).

author: Coosje Veldkamp
date: 07 October 2024
---

## Upcoming Workshop: [Stimulating the (Re)Use of FAIR Research Data Among Researchers: Strategies and Solutions](https://opensciencefestival.nl/en/programme/stimulating-the-reuse-of-fair-research-data-among-researchers-strategies-and-solutions-double-workshop)

Researchers routinely use insights from previous work – but typically they use publications more often and more intensively than the underlying data. While significant efforts have been invested in ensuring the production of FAIR data, an equally critical aspect - stimulating the reuse of data - remains relatively underexplored. This interactive workshop aims to address this gap by engaging participants in discussions and activities that will uncover barriers to data reuse and develop actionable strategies to enhance the consumption of FAIR research data among researchers.

During this workshop, research support staff, researchers, funders, policy makers and others will be working collaboratively on these objectives:
- *Identifying barriers and exploring motivators:* taking into account differences between research domains, participants will identify common obstacles that hinder the (re)use of FAIR data, including technical, cultural, and policy-related challenges. We will also explore what motivates researchers to reuse data, examining successful case studies and reviewing results from studies on this topic.
- *Developing strategies:* participants will collaborate to develop practical strategies and recommendations to promote the (re)use of FAIR data.
- *Action plan:* participants will be provided with a template to create an action plan tailored to their research domains or research communities, aiming to foster a culture of data reuse.
- *Continued collaboration and community development:* participants will be invited to share their action plans in a common online space and collaborate in a newly formed community on stimulating data (re)use.

Organized by: [Hugo Quené](https://www.uu.nl/medewerkers/HQuene), [Aleid de Jong](https://www.uu.nl/medewerkers/AYdeJong), [Jacques Flores](https://www.uu.nl/staff/JPFlores), [Jonathan de Bruin](https://www.uu.nl/medewerkers/JdeBruin1), and [Coosje Veldkamp](https://www.uu.nl/medewerkers/CLSVeldkamp), Utrecht University The workshop will be held at the [Netherlands National Open Science Festival](https://opensciencefestival.nl/) at Maastricht University on October 22, 2024.
