---
title: "Programming Café, September 2024"
description: |

author: The Research Data Services Team
date: 03 September 2024
---

Event 
Time and date: 12 September 2024 - 15 to 17hr
Location: Bucheliuszaal 6.18, Universiteitsbibliotheek (Utrecht Science Park)

Do you want to improve your programming skills, meet colleagues interested in coding, or ask questions related to research software? Pick up your laptop and come to the Programming Café!

In this monthly meet-up, we will share knowledge about programming through short presentations, work on software projects, and help each other with challenges in working with code and data.

This month’s theme: _Introducing iBridges_ 

Do you already use Yoda to store your data? Would you like to find out what else the system can do?

In this talk, we will demonstrate how to leverage the full potential of Yoda through a new tool box called iBridges. iBridges consists of a python library to easily program against data, a command line tool for streamlined uploading and downloading of data, and a graphical user interface to enhance the experience of using Yoda.
We will present a compute workflow that uses data in Yoda, generates results, and levels them with data. Subsequently, the results can be found by a non-programming user employing the GUI and downloading the results of the compute workflow. Join us to explore the functionality hidden inside of Yoda.

What to expect 

During the Programming Café, you can work on your own project and share knowledge in a community setting. You can also bring your programming questions, bugs, and problems to discuss or resolve with members of Information Technology Support, Research Data Services, and researchers attending the café.
In addition, each Programming Café will have a special theme. This is typically a short presentation or demonstration of (maximum) half an hour. We are always looking for suggestions on themes and people who want to present something. Don’t hesitate to send an email to info.rdm@uu.nl if you want to provide a suggestion or give a presentation!

Who can attend
 
Everyone is welcome at the Programming Café! You can be of any skill level and at any stage in working with your code and data. While many attendees will be R or Python users, people interested in other programming languages and software are invited as well.

Full information can be found at (uu.nl/rdm)[https://www.uu.nl/en/events/programming-cafe-12-september-2024]
