---
title: "Research Data Services -- Evaluation Framework"
description: |

author: Dan Rudmann
date: 25 November 2024
---

RDS works to facilitate culture change in research toward more Open & FAIR practices. 

RDS fulfills this vision by centering transparency, working in a way that reflects the processes we promote. As a service department, our goal is to empower the people we work with to realise their own agency and sovereignty in bringing about change in research practices and culture. 

In order to meet the shared goal of our office, RDS engages in intersecting activities: 

##Guidance##
RDS at the UB is an expertise center for developing practices related to research processes and data management within Utrecht University. We offer advice to researchers, inform administrative policy, and share knowledge with colleagues to bring about a wider understanding of diverse perspectives and actions that align research practices with our organisational [mission.](https://www.uu.nl/en/organisation/profile/mission-and-strategy)

##Training##
RDS translates its knowledge into a series of workshops and training sessions that are offered at the university libraries. We organise and teach those sessions to work with researchers on issues in research software management, research data, and their related digital competencies. Trainings are offered both in-person and as persistent online modules.

##Community##
Engendering cooperation is at the core of RDS efforts. We bring people together, both within and across organisational boundaries, to exchange knowledge by identifying and supporting judicious connections. RDS focuses simultaneously on the content of research processes and the experience of facilitating change.

##Infrastructure##
RDS tends a knowledge base on technical infrastructure that supports research processes. We leverage our embedded positions to surface researcher needs and communicate those to developers to improve technical capabilities. Simultaneously, RDS stewards the social infrastructure that promotes community-led progress in research processes.

##Meta-Science##
RDS team members are thought leaders in research processes and help increase collective literacy on pressing issues in open science. We explore emerging trends in research intelligence, research information, and bibliometrics, along with their relation to data. 
