---
title: "Upcoming Workshop at the National Open Science Festival with RDS and UDCC: Building the Commons"
description: Utrecht librarians join colleagues from the VU, TDCC-NES, and OSC-NL for an interactive workshop on networked and open ways of working at knowledge organisations in the Netherlands.

author: Dan Rudmann
date: 03 October 2024
---
Upcoming Workshop: Building the Commons

The implementation of Open Science across the Netherlands is beginning to reorient the way people at knowledge organisations structure their work. Institutions are affirming these changes by reimaging programs for Recognition & Reward and developing innovative networks such as DCCs (Digital Competence Centers). By exploring these modes of support and collaboration across the Netherlands, this interactive session will co-design structures that facilitate community, valorisation, and care as intrinsic to science.

The workshop “Building the Commons: How Open Science and DCCs Bring About New Ways of Working” will be divided into three parts. The initial presentation will establish a shared foundation for ideas around open and networked modes of knowledge production, introducing the concept of the commons. The second section will showcase a series of spaces already beginning to enact this type of cooperation within and among organisations in the Netherlands, including Utrecht DCC, VU Art Science, the Dutch Open Science Communities, and the national TDCC. Finally, participants will engage in a collective exercise to design common networks across their communities. The session is intended for people working in research and research support who are interested in the connections and infrastructure that generate Open Science.

During this session, we will assert that the present moment in the Netherlands is an extraordinary opportunity to build such knowledge commons due to the national commitment to Open Science and the unique affiliations among present knowledge workers. We seek to build upon this collaborative spirit to render our work more inclusive, engaged, diverse, equitable, and meaningful. People attending this session will gain insight into projects that rethink cooperation as well as a framework and lexicon to render those types of efforts more visible and resilient. The output will be designs and resources that help people participate in and replicate open and networked forms of knowledge production.

Organized by: 
Coosje Veldkamp, Utrecht University
Anna van ‘t Veer, OSC-NL 
Martine de Vos, Utrecht University 
Nicole Emmenegger, TDCC–SSH
Dan Rudmann, Utrecht University
Lieke de Boer, Netherlands eScience Center
Lena Karvovskaya, Vrije Universiteit
Lilli van Wielink, Utrecht University

The workshop will be held at the [Netherlands National Open Science Festival](https://opensciencefestival.nl/) at Maastricht University on October 22, 2024.
