---
title: "UDCC Forum Dialogue – Digital Autonomy"
description: |

author: Dan Rudmann and Mees van Stiphout
date: 17 February 2026
---

On June 24, 2025, the UDCC gathered together for the final forum of its first year. In just ten months time, research staff throughout the university built a new venue for knowledge exchange and professional development in digital competencies. Meeting monthly to share questions, form new initiatives, and learn from one another, the UDCC Forum has demonstrated the significance of collaboration and mutual support. In recent months, the community has expanded to welcome people from other institutions based in the Utrecht area as well as national counterparts.  

Both the attendance and atmosphere was heightened at this particular Forum due to the relevance and interest for our special topic: a panel discussion on efforts to envision and build a digitally autonomous Utrecht University. 

## Open Agenda
The first hour of the Forum brought updates and new questions from across the UU. Each month, community members share knowledge on emerging issues in research data management, open science, and digital competency issues. Here we began to plot Bèta’s forthcoming [FAIR-R and Open Data Week](https://science-data-support.sites.uu.nl/faculty-services-support/fair-r-and-open-data-week/), compare parallel efforts in data cleaning for repositories across faculties, and [celebrate national recognition for our own data engineer Raoul Schram](https://www.surf.nl/en/article/winners-research-support-champion-award-2025#raoul-schram).

Johan Bokslag, from the University Medical Centre Utrecht, also joined us to share new systems and initiatives to support the Health Data Space. Bokslag spoke about empowering people to access and use their own health data. The initiative is still at an early phase, and in particular issues of governance and assessment would still need to be worked out. A sign that many of our digital possibilities remain truly mediated by our social connectivity. 

## Digital Autonomy
For the first time, the UDCC Forum brought together a panel of colleagues from across the university to discuss a critical issue that touches all of our work. Chaired by [André van Kooij](https://www.uu.nl/staff/AvanKooij) from the Centre for Digital Humanities, the panel consisted of [Bawan Amin](https://www.uu.nl/staff/BKRAmin), research support officer at FSW, [Jeroen Bosman](https://www.uu.nl/staff/JMBosman) from the university library, [Pui-Kei Fung](https://www.uu.nl/staff/PKFung/CV), IT Architect, and [Tim van Neerbos](https://www.uu.nl/staff/TMvanNeerbos), Enterprise and IT Architect.

To begin, van Kooij introduced and contextualised the panel, citing recent geo-political events as underscoring the need for greater digital autonomy for all organisations, including UU. Elaborating on the right to privacy, self-determination, and Open Science principles, van Kooij argued that dependencies upon certain powerful governments and commercial technology companies are ultimately incompatible with, and unsustainable for, the goals of a research and education institution. 

With this shared foundation, Tim van Neerbos introduced the strategies and actions taking shape to realise digital autonomy at our university. As one of the architects of the university’s digital strategy, van Neerbos is currently scoping a two-year project that will gain insights, guardrails, and roadmaps toward digital autonomy. What was clear from van Neerbos was both the severity and thoughtfulness in approaching the issue. The architects at the university realise the comprehensive nature of the project but remain determined to bring about change. To this end, van Neerbos presented the Utrecht University Capability Model to assess the risks and trade-offs to realising the goal. Van Neerbos was clear that trade-offs would not always be comfortable or convenient, but that the possibilities in autonomy would often outweigh those challenges.  

Pui-Kei Fung built upon van Neerbos’ discussion by focusing on researcher concerns in an institutional transition toward digital autonomy. Fung identifies three potential challenges that could impact researchers with emerging systems: security, data storage, and usability. Would a new system for researchers compromise the security of and access to their work? How might researchers have to adjust their data storage workflows? And would digitally autonomous tools lack the clear user experience features and capabilities that people have grown to expect? But such potential difficulties are not insurmountable. Fung cites the recent [open letter from researchers calling for digital autonomy](https://cdh.uu.nl/2025/03/28/open-letter-petition-call-for-digital-autonomy-uu/) as a strong indication of willingness to work through such problems. The determining factor in a successful transition to digital autonomy, then, is building trust between researchers and the university’s digital architects and support staff. To establish such trust, Fung approaches this work by always centering the researchers to be mindful of their experience and values in making the transition.

Bawan Amin spoke about Open Science and the role of the university in society. Working daily alongside researchers, Amin witnesses the pressures they face in making their work open, particularly in regard to a culture of scholarly publishing that favours quantity over quality. Researchers often are put in an unfortunate position to compromise their ideals in favour of a global scientific structure that continues to favour “high-impact” commercial publishing. When researchers have less agency in deciding how their work becomes a publication, they unwittingly abdicate their digital autonomy. Many publishers are able to reserve rights over researcher data and restrict that data from public view, which Amin explains both hinders reproducibility and can lead to fraud. Amin illustrates the ways in which digital autonomy has far reaching implications for many of the ambitions that Utrecht University has set over the past decade in becoming an Open Science oriented institution. Digital autonomy, therefore, becomes a critical aspect in achieving our goals as a university. 

Jeroen Bosman, [whose recent work also addresses the interdependence of Open Science and digital autonomy](https://upstream.force11.org/the-resilience-of-open-science-in-times-of-crisis/), presented three provocations to initiate the transition to a digitally autonomous university: 1. It is helpful to connect different perspectives; 2. Make it an activity rather than a state; and 3. Enjoy the suffering. Such statements are informed by Bosman’s record of assisting the university in taking initiative in culture change. Indeed, Bosman shows us that the process of achieving autonomy in our digital systems is as crucial as the goal. That process, Bosman explains, if conducted carefully, can increase the freedom and agency of our researchers and lead to a more inclusive and diverse research culture. Bosman outlines a strategy of resilience that does not seek to duck away from the storms ahead, but rather allow turbulent times and new developments to reify the principles that we strive toward and compel us to act. 

## What's Next
The panel discussion surfaced a delineation between technical and social solutions. While their coordination is crucial, the cultural changes to allow for digital autonomy were perhaps the most crucial in bringing about meaningful interventions. Panelists advocated for greater transparency to allow for empathy in the face of change. All agreed that in our position as research support staff, our value is increased through accountability and trust. 

How might we come together as a community to help one another through transitions? Seeds of a good answer were present in this meeting. 

## For More
The UDCC Forum is a monthly gathering of Utrecht University personnel working to develop digital competencies throughout the university. All are welcome. Contact the UDCC support team or visit [uu.nl/dcc](https://uu.nl/dcc) for information on forthcoming events.  
